
@startuml

	' // scale 600 width
	
	' allow_mixing
	' !pragma teoz true
	
	skinparam componentstyle uml2
	
	hide empty description
	
	skinparam linetype polyline
	' skinparam linetype ortho
	' left to right direction
	
	!function $kw($key_word)
	' // !return "**<color blue>" + $key_word + "</color>**"
	!return "**" + $key_word + "**"
	!endfunction
	
	!function $kop($key_operator)
	' // !return "**<color blue>" + $key_operator + "</color>**"
	!return "**" + $key_operator + "**"
	!endfunction
	
	!function $ks($key_symbol)
	' // !return "**<color blue>" + $key_symbol + "</color>**"
	!return "**" + $key_symbol + "**"
	!endfunction
	
	!function $param($p)
	' // !return "**<color darkred>" + $p + "</color>**"
	!return "**" + $p + "**"
	!endfunction
	
	!$natural = "**<color darkred>&#9838;</color>**"
	
	!$tp_path = "#Green,thickness=2"
	
	<style>
		note {
			backgroundcolor white
			shadowing 0
			linecolor transparent
			FontSize 35
		}
	</style>
	
	skinparam backgroundColor White
	
	skinparam arrow {
		Thickness 3
	}
	
	skinparam RoundCorner 0
	
	skinparam state {
		StartColor Green
		EndColor Red
		'Attribut pour les transitions
		ArrowColor Black
		ArrowColor<< Else >> Orange
		'Attribut par défaut pour les états
		BorderColor Black
		BorderThickness 3
		BackgroundColor Wheat
		'Attribut pour les états composites
		BackgroundColor<< System            >> LightGrey
		BackgroundColor<< Statemachine      >> GenericDisplay
		BackgroundColor<< Machine           >> GenericDisplay
		BackgroundColor<< Instance          >> GenericDisplay
		BackgroundColor<< Composite         >> GenericDisplay
		'Attribut pour les états simples
		BackgroundColor<< simple_hierarchic >> PaleTurquoise
		BackgroundColor<< simple            >> #E6E6E6
		BackgroundColor<< start             >> #E6E6E6
		BackgroundColor<< final             >> #E6E6E6 //#E6F4EA
		BackgroundColor<< pass              >> GreenYellow
		BackgroundColor<< sync              >> Aqua
		'Attribut pour les pseudo-états
		BackgroundColor<< pseudostate       >> Lavender
		BackgroundColor<< initial           >> GreenYellow
		BackgroundColor<< junction          >> #FFF7CC
		BackgroundColor<< choice            >> Orange
		BackgroundColor<< fork              >> #FFF7CC
		BackgroundColor<< join              >> SpringGreen
		BackgroundColor<< dhistory          >> SpringGreen
		BackgroundColor<< shistory          >> SpringGreen
		BackgroundColor<< return            >> OrangeRed
		BackgroundColor<< terminal          >> #E6E6E6 // #F8E1E1
		FontColor Black
		FontName Times
		FontSize 35
	}

state "System CoffeeMachine" as CoffeeMachine__2569298167400 << System >> {
	state "SM" as SM__2569297512792 << Statemachine >> {
		state "startup" as startup__2569300879432 << Initial >>

		startup__2569300879432--> idle__2569301826392
		note on link #white
			**tr_0**
			sum := 0 $ks(";")
		end note

		state "idle" as idle__2569301826392 << Simple >>

		idle__2569301826392--> check__2569301828120
		note on link #white
			**tr_1**
			$kw("input") Coin(c) $ks(";")
			sum := (sum $kop("+") c) $ks(";")
		end note

		state "check" as check__2569301828120 << Simple >>

		check__2569301828120--> idle__2569301826392
		note on link #white
			**tr_2**
			$kw("guard") (sum $kop("<") PRICE) $ks(";")
			$kw("output") RestMon((PRICE $kop("+") ($kop("-") sum))) $ks(";")
		end note

		check__2569301828120--> idle__2569301826392
		note on link #white
			**tr_3**
			$kw("guard") (sum $kop(">=") PRICE) $ks(";")
			$kw("output") Coffee $ks(";")
			sum := 0 $ks(";")
		end note

	}

}

@enduml


