
@startuml symbex_graph

' // scale 600 width

hide empty description

skinparam linetype polyline
' skinparam linetype ortho
' left to right direction

skinparam backgroundColor White
skinparam backgroundColor White
skinparam noteBorderColor White
skinparam shadowing false
skinparam notefontsize 16
skinparam notefontname Verdana
'skinparam notefontname Consolas
'skinparam noteShadowing false

skinparam state {
	StartColor Green
	EndColor Red

	'Attribut pour les transitions
	ArrowColor Black
	ArrowColor<< Else >> Orange

	'Attribut par défaut pour les états
	BorderColor Gray
	BackgroundColor Wheat

	'Attribut pour les noeuds/feuilles du graphes SymBex
	BackgroundColor<< DefaultNode >> LightBlue

	BackgroundColor<< RedondancyTargetSource >> Green
	BackgroundColor<< RedondancyTargetNode >> GreenYellow

	BackgroundColor<< PassedNode >> GreenYellow
	BackgroundColor<< FailedNode >> Red
	BackgroundColor<< InconclusiveNode >> Orange
	BackgroundColor<< AbortedNode >> Orange
	BackgroundColor<< WarningNode >> Orange
	BackgroundColor<< ErrorNode >> Red
	BackgroundColor<< AlertNode >> Red
	BackgroundColor<< ExitNode >> Red

	'Attribut pour les paths du graphes SymBex
	BackgroundColor<< PassedPath >> LawnGreen
	BackgroundColor<< FailedPath >> Red
	BackgroundColor<< InconclusiveNodePath >> Orange
	BackgroundColor<< AbortedPath >> Red

	FontColor Black
	FontName Times
	FontSize 14
}



state "EC 0" as EC0 << DefaultNode >>

EC0: < ev:1 , h:0 , w:1 > 
EC0: Example02_Dummy_S:q0
note left of EC0
$time = 0
	# = 0
	_clock_index_ = 0
	sum = sum_0
	x = x_0
	cl = 0
	
end note

EC0 -down-> EC1

state "EC 1" as EC1 << DefaultNode >>

EC1: < ev:2 , h:1 , w:1 > 
EC1: Example02_Dummy_S:q0
note left of EC1
sum = 0
	
end note

EC1 -down-> EC2

state "EC 2" as EC2 << PassedNode >>

EC2: < ev:3 , h:2 , w:1 > 
EC2: Example02_Dummy_S:q1
note left of EC2
PC: ((0 <= (x_1 + -1)) && (x_1 <= 10))
	$time = #_0
	# = #_0
	sum = x_1
	x = x_1
	
end note
EC2: ----
EC2: transition::Example02_Dummy_S.Example02_Dummy_SM.q0.tr1

EC2 -down-> EC3

EC2 -down-> EC4

state "EC 3" as EC3 << PassedNode >>

EC3: < ev:4 , h:3 , w:1 > 
EC3: Example02_Dummy_S:q0
note left of EC3
PC: (((#_1 + x_1) == 42) && (0 <= (x_1 + -1)) && (x_1 <= 5) && (x_1 <= 10))
	$time = (#_0 + #_1)
	# = #_1
	cl = #_1
	
end note
EC3: ----
EC3: transition::Example02_Dummy_S.Example02_Dummy_SM.q1.tr2

EC3 -down-> EC5

state "EC 4" as EC4 << PassedNode >>

EC4: < ev:5 , h:3 , w:2 > 
EC4: Example02_Dummy_S:q0
note left of EC4
PC: (((#_1 + x_1) == 42) && (0 <= (x_1 + -1)) && (x_1 <= 10) && (x_1 > 5))
	$time = (#_0 + #_1)
	# = #_1
	cl = #_1
	
end note
EC4: ----
EC4: transition::Example02_Dummy_S.Example02_Dummy_SM.q1.tr3

state "EC 5" as EC5 << DefaultNode >>

EC5: < ev:6 , h:4 , w:1 > 
EC5: Example02_Dummy_S:q1
note left of EC5
PC: (((#_1 + x_1) == 42) && (0 <= (x_1 + -1)) && (0 <= (x_2 + -1)) && (x_1 <= 5) 
	&& (x_1 <= 10) && (x_2 <= 10))
	$time = (#_0 + #_1 + #_2)
	# = #_2
	sum = (x_1 + x_2)
	x = x_2
	cl = 0
	
end note

EC5 -down-> EC8

state "EC 8" as EC8 << DefaultNode >>

EC8: < ev:8 , h:5 , w:3 > 
EC8: Example02_Dummy_S:q0
note left of EC8
PC: (((#_1 + x_1) == 42) && ((#_4 + x_2) == 42) && (0 <= (x_1 + -1)) && (0 <= 
	(x_2 + -1)) && (x_1 <= 5) && (x_1 <= 10) && (x_2 <= 10) && (x_2 > 5))
	$time = (#_0 + #_1 + #_2 + #_4)
	# = #_4
	cl = #_4
	
end note

EC8 -down-> EC11

state "EC 11" as EC11 << ExitNode >>

EC11: < ev:0 , h:6 , w:4 > 
EC11: Example02_Dummy_S:q2
note left of EC11
PC: (((#_1 + x_1) == 42) && ((#_4 + x_2) == 42) && (0 <= (x_1 + -1)) && (0 <= 
	(x_2 + -1)) && (x_1 <= 5) && (x_1 <= 10) && (x_2 <= 10) && (x_2 > 5) && ((x_1 + 
	x_2) >= 15))
	$time = (#_0 + #_1 + #_2 + #_4 + #_6)
	# = #_6
	cl = (#_4 + #_6)
	
end note
EC11: ----
EC11: transition::Example02_Dummy_S.Example02_Dummy_SM.q0.tr4\nFINALIZE
EC11: STATEMENT-EXIT & COVERAGE-ELEMENT
@enduml