
@startuml symbex_graph

' // scale 600 width

hide empty description

skinparam linetype polyline
' skinparam linetype ortho
' left to right direction

skinparam backgroundColor White
skinparam backgroundColor White
skinparam noteBorderColor White
skinparam shadowing false
skinparam notefontsize 16
skinparam notefontname Verdana
'skinparam notefontname Consolas
'skinparam noteShadowing false

skinparam state {
	StartColor Green
	EndColor Red

	'Attribut pour les transitions
	ArrowColor Black
	ArrowColor<< Else >> Orange

	'Attribut par défaut pour les états
	BorderColor Gray
	BackgroundColor Wheat

	'Attribut pour les noeuds/feuilles du graphes SymBex
	BackgroundColor<< DefaultNode >> LightBlue

	BackgroundColor<< RedondancyTargetSource >> Green
	BackgroundColor<< RedondancyTargetNode >> GreenYellow

	BackgroundColor<< PassedNode >> GreenYellow
	BackgroundColor<< FailedNode >> Red
	BackgroundColor<< InconclusiveNode >> Orange
	BackgroundColor<< AbortedNode >> Orange
	BackgroundColor<< WarningNode >> Orange
	BackgroundColor<< ErrorNode >> Red
	BackgroundColor<< AlertNode >> Red
	BackgroundColor<< ExitNode >> Red

	'Attribut pour les paths du graphes SymBex
	BackgroundColor<< PassedPath >> LawnGreen
	BackgroundColor<< FailedPath >> Red
	BackgroundColor<< InconclusiveNodePath >> Orange
	BackgroundColor<< AbortedPath >> Red

	FontColor Black
	FontName Times
	FontSize 14
}



state "EC 0" as EC0 << DefaultNode >>

EC0: < ev:1 , h:0 , w:1 > 
EC0: atm_syst:Idle
note left of EC0
$time = 0
	z = 0
	_clock_index_ = 0
	cl = 0
	wtb = 5
	threshold = 10
	amount = 0
	x = 0
	auth_ok = false
	
end note

EC0 -down-> EC1

state "EC 1" as EC1 << DefaultNode >>

EC1: < ev:2 , h:1 , w:1 > 
EC1: atm_syst:Idle

EC1 -down-> EC2

state "EC 2" as EC2 << PassedNode >>

EC2: < ev:3 , h:2 , w:1 > 
EC2: atm_syst:Ready
note left of EC2
$time = z_0
	z = z_0
	cl = z_0
	
end note
EC2: ----
EC2: tpid#1->Idle.t_init

EC2 -down-> EC3

state "EC 3" as EC3 << PassedNode >>

EC3: < ev:4 , h:3 , w:1 > 
EC3: atm_syst:Decision
note left of EC3
$time = (z_0 + z_1)
	z = z_1
	cl = (z_0 + z_1)
	x = x_0
	
end note
EC3: ----
EC3: tpid#2->Ready.t_receive

EC3 -down-> EC5

state "EC 5" as EC5 << PassedNode >>

EC5: < ev:5 , h:4 , w:2 > 
EC5: atm_syst:WaitingAuth
note left of EC5
PC: (x_0 >= 10)
	$time = (z_0 + z_1 + z_2)
	z = z_2
	cl = 0
	amount = x_0
	
end note
EC5: ----
EC5: tpid#3->Decision.t_valid

EC5 -down-> EC7

state "EC 7" as EC7 << PassedPath >>

EC7: < ev:7 , h:5 , w:3 > 
EC7: atm_syst:givecash
note left of EC7
PC: ((auth_ok_0 == true) && (x_0 >= 10))
	$time = (z_0 + z_1 + z_2 + z_3)
	z = z_3
	cl = z_3
	auth_ok = auth_ok_0
	
end note
EC7: ----
EC7: tpid#4->WaitingAuth.t_auth_cash
@enduml