@startuml

hide empty description

skinparam backgroundColor White
skinparam backgroundColor White
skinparam noteBorderColor White
skinparam shadowing false
skinparam notefontsize 16
skinparam notefontname Verdana
'skinparam notefontname Consolas
'skinparam noteShadowing false

skinparam state {
	StartColor Green
	EndColor Red

	'Attribut pour les transitions
	ArrowColor Black
	ArrowColor<< Else >> Orange

	'Attribut par défaut pour les états
	BorderColor Gray
	BackgroundColor Wheat

	'Attribut pour les états composites
	BackgroundColor<< System       >> Turquoise
	BackgroundColor<< Statemachine >> DodgerBlue
	BackgroundColor<< Machine      >> SpringGreen
	BackgroundColor<< Instance     >> Orchid
	BackgroundColor<< Composite    >> SpringGreen

	'Attribut pour les états simples
	BackgroundColor<< Simple >> PaleTurquoise
	BackgroundColor<< Start  >> Green
	BackgroundColor<< Final  >> Red
	BackgroundColor<< Sync   >> Aqua

	'Attribut pour les pseudo-états
	BackgroundColor<< Pseudo   >> Lavender
	BackgroundColor<< Initial  >> GreenYellow
	BackgroundColor<< Junction >> GreenYellow
	BackgroundColor<< Choice   >> Orange
	BackgroundColor<< Fork     >> SpringGreen
	BackgroundColor<< Junction >> SpringGreen
	BackgroundColor<< DeepHistory    >> SpringGreen
	BackgroundColor<< ShallowHistory >> SpringGreen
	BackgroundColor<< Return   >>  OrangeRed
	BackgroundColor<< Terminal >> Red

	FontColor Black
	FontName Times
	FontSize 14
}

state "System PingPong" as PingPong__2566794833960 << System >> {
	state "Alice" as Alice__2566797138488 << Statemachine >> {
		state "a0" as a0__2566799306776 << Start >>

		a0__2566799306776--> a0__2566799306776
		note on link #white
			**a0_rcv_ignore:**
			{
				guard (aclk <= Timeout);
				localPC := (localPC && (aclk <= Timeout));
			}
			input Pong(n, timeEmit);
			{
				guard (timeEmit <= localTime);
				localPC := (localPC && (timeEmit <= localTime));
			}
		end note

		a0__2566799306776--> a1__2566798976312
		note on link #white
			**a0_snd:**
			{
				guard (aclk <= Timeout);
				localPC := (localPC && (aclk <= Timeout));
			}
			output Ping(seq, localTime);
		end note

		state "a1" as a1__2566798976312 << Simple >>

		a1__2566798976312--> a1__2566798976312
		note on link #white
			**a1_rcv_ignore:**
			{
				guard (aclk <= Timeout);
				localPC := (localPC && (aclk <= Timeout));
			}
			input Pong(n, timeEmit);
			{
				guard (timeEmit <= localTime);
				localPC := (localPC && (timeEmit <= localTime));
			}
			{
				guard (n < seq);
				localPC := (localPC && (n < seq));
			}
		end note

		a1__2566798976312--> a2__2566799091368
		note on link #white
			**a1_rcv:**
			{
				guard (aclk <= Timeout);
				localPC := (localPC && (aclk <= Timeout));
			}
			input Pong(n, timeEmit);
			{
				guard (timeEmit <= localTime);
				localPC := (localPC && (timeEmit <= localTime));
			}
			{
				guard (n == seq);
				localPC := (localPC && (n == seq));
			}
			aclk := 0;
		end note

		a1__2566798976312--> a0__2566799306776
		note on link #white
			**a1_warning:**
			{
				guard (aclk == Timeout);
				localPC := (localPC && (aclk == Timeout));
			}
			output Warning;
			seq := (+ 1);
			aclk := 0;
		end note

		state "a2" as a2__2566799091368 << Simple >>

		a2__2566799091368--> a2__2566799091368
		note on link #white
			**a2_rcv_ignore:**
			{
				guard (aclk <= Interval);
				localPC := (localPC && (aclk <= Interval));
			}
			input Pong(n, timeEmit);
			{
				guard (timeEmit <= localTime);
				localPC := (localPC && (timeEmit <= localTime));
			}
		end note

		a2__2566799091368--> a0__2566799306776
		note on link #white
			**a2_new_interval:**
			{
				guard (aclk == Interval);
				localPC := (localPC && (aclk == Interval));
			}
			seq := (+ 1);
			aclk := 0;
		end note

	}
	--
	state "Bob" as Bob__2566799962200 << Statemachine >> {
		state "b0" as b0__2566799965480 << Start >>

		b0__2566799965480--> b1__2566799938200
		note on link #white
			**b0_rcv:**
			input Ping(p, timeEmit);
			{
				guard (timeEmit <= localTime);
				localPC := (localPC && (timeEmit <= localTime));
			}
			bclk := 0;
		end note

		state "b1" as b1__2566799938200 << Simple >>

		b1__2566799938200--> b1__2566799938200
		note on link #white
			**b1_rcv_loop:**
			{
				guard (bclk <= Unit);
				localPC := (localPC && (bclk <= Unit));
			}
			input Ping(p, timeEmit);
			{
				guard (timeEmit <= localTime);
				localPC := (localPC && (timeEmit <= localTime));
			}
		end note

		b1__2566799938200--> b0__2566799965480
		note on link #white
			**b1_snd:**
			{
				guard (bclk <= Unit);
				localPC := (localPC && (bclk <= Unit));
			}
			output Pong(p, localTime);
		end note

	}

}
@enduml

